
- name: Verificar lista pve
  stat: path=/etc/apt/sources.list.d/pve-enterprise.list
  register: pvelista

- name: Renomear pve lista
  shell: rm /etc/apt/sources.list.d/pve-enterprise.list ; apt-get update
  when: pvelista
  ignore_errors: yes

- name: Instala pacotes do promox
  apt: name={{ item }} state=present update_cache=no
  with_items: "{{packagesproxmox}}"
  tags:
    - instalarpacotes
  ignore_errors: yes

- name: Verificar serviço cron
  service: name=cron state=started enabled=yes

- name: Verificar serviço ssh
  service: name=ssh state=started enabled=yes

- name: Verificar permissões do /etc/ssh
  file: path=/etc/ssh state=directory owner=root group=root mode=0755

- name: Copiar configuração ssh
  copy: dest=/etc/ssh src=proxmox/etc/ssh/  mode=0644 owner=root group=root
  notify: ssh

- name: Copiar configuração stunnel
  copy: dest=/etc/stunnel src=proxmox/etc/stunnel/  mode=0644 owner=root group=root

- name: Copia .gitignore
  copy: dest=/etc/.gitignore src=proxmox/proxmoxgitignoreetc  mode=0700 owner=root group=root

- name: Rodar metastore
  command: /usr/bin/metastore -s creates=/etc/.metadata chdir=/etc

- name: Rodar git init
  command: /usr/bin/git init creates=/etc/.git chdir=/etc

- name: Definir permissões de diretorio git do etc
  file: path=/etc/.git state=directory mode=0700 owner=root group=root
